config/routes.rb
Rails.application.routes.draw do
  
  
  get 'login', to: 'sessions#new', as: 'new_session'  
  post 'login', to: 'sessions#create', as: 'session'   
  get 'logout', to: 'sessions#destroy'
  
  resources :listings
  resources :crops_labels
  resources :crop_categories
  resources :crops
  resources :users
  resources :password_resets, only: [:new, :create, :edit, :update]
  

  

  get "password_resets/new"
  get "password_resets/edit"
  
  get '/profile', to: 'users#profile', as: 'profile'

  
  root to: "home#index"
  #root "users#new"
  get "users/index"
  get "home/about"

  #login/logout routes
  
 
  #get "up" => "rails/health#show", as: :rails_health_check


end

app/models/listing.rb
class Listing < ApplicationRecord
  belongs_to :crop
  belongs_to :user
  
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: %i[ show edit update destroy ]

  # GET /listings or /listings.json
  def index
    @listings = Listing.all
  end

  # GET /listings/1 or /listings/1.json
  def show
  end

  # GET /listings/new
  def new
    @listing = Listing.new
  end

  # GET /listings/1/edit
  def edit
  end

  # POST /listings or /listings.json
  def create
    @listing = Listing.new(listing_params)

    respond_to do |format|
      if @listing.save
        format.html { redirect_to @listing, notice: "Listing was successfully created." }
        format.json { render :show, status: :created, location: @listing }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /listings/1 or /listings/1.json
  def update
    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to @listing, notice: "Listing was successfully updated." }
        format.json { render :show, status: :ok, location: @listing }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1 or /listings/1.json
  def destroy
    @listing.destroy!

    respond_to do |format|
      format.html { redirect_to listings_path, status: :see_other, notice: "Listing was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing
      @listing = Listing.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def listing_params
      params.expect(listing: [ :title, :description, :price, :location, :crop_id, :user_id ])
    end
    
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/listings/_form.html.erb
<%= form_with(model: listing) do |form| %>
  <% if listing.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(listing.errors.count, "error") %> prohibited this listing from being saved:</h2>

      <ul>
        <% listing.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="container py-5 h-100">
    <div class="row justify-content-center align-items-center h-150">
      <div class="col-12 col-lg-9 col-xl-7">
        <div class="card shadow-2-strong card-registration" style="border-radius: 15px;">
          <div class="card-body p-4 p-md-5">
          <h3 class="mb-4 pb-2 pb-md-0 mb-md-5 text-center">List Your Crops</h3>
  <form>
    <div class="field form-group">
    <b>Welcome ,<%= current_user&.name %></b>
    <%# form.label :user_id, current_user&.name, style: "display: block" %>
    <%# form.collection_select :user_id, current_user, :id, :name, prompt: "Choose a user", class: "form-control" %>
    </div>
    <br>

    <div class="field form-group">
      <%=form.label :title , style: "display: block" %>
      <%= form.text_field :title, required:true,class:"form-control" , placeholder:"Title for Your Product"%>
    </div>
    <br>

    <div class="field form-group">
      <%= form.label :description, style: "display: block" %>
      <%= form.text_field :description,required: true ,class:"form-control" ,placeholder:"Descrption"  %>
    </div>
    <br>

    <div class="field form-group">
    <%= form.label :location, style: "display: block" %>
    <%= form.text_field :location,required: true ,class:"form-control" ,placeholder:"location"  %>
    </div>
    <br>

    <div class="field form-group">
    <%= form.label :price, style: "display: block" %>
    <%= form.text_field :price,required: true ,class:"form-control" ,placeholder:"Price per Kg"  %>
    </div>
    <br>

    <div class="field form-group">
    <%= form.label :crop_id, "Select Crop", style: "display: block" %>
    <%= form.collection_select:crop_id, Crop.all, :id, :name, prompt: "Choose a Crops", class: "form-control" %>
    </div>
    <br>

  <div style="text-align: center; margin-top: 20px;",class="btn btn-primary">
      <%= form.submit %>
    </div>
  
  </form>
          </div>
        </div>
      </div>
    </div>
  </div>


<% end %>

app/views/listings/_listing.html.erb
<div id="<%= dom_id listing %>">

<body class="bg-dark text-white">

<div class="card shadow text-bg-light text-black mb-3 " style="width: 100%; max-width: 300px;">
  
<p>
    <strong>Title:</strong>
    <%= listing.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= listing.description %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= listing.price %>
  </p>

  <p>
    <strong>Location:</strong>
    <%= listing.location %>
  </p>

  <p>
    <strong>Crop:</strong>
    <%= listing.crop.name %>
  </p>

  <p>
    <strong>User:</strong>
    <%= listing.user.name%>
  </p>

  <p>
  <%= link_to "Show", listing , class: "btn btn-outline-dark mx-2"%>
  
  <%= link_to "Create", new_listing_path, class: "btn btn-outline-dark mx-2" %>
  </p>
  

</div>

app/views/listings/edit.html.erb
<% content_for :title, "Editing listing" %>

<h1>Editing listing</h1>

<%= render "form", listing: @listing %>

<br>

<div>
  <%= link_to "Show this listing", @listing %> |
  <%= link_to "Back to listings", listings_path %>
</div>

app/views/listings/index.html.erb
<% content_for :title, "Listings" %>

<h1>Listings</h1>

<div id="listings">
  <% @listings.each do |listing| %>
    <%= render listing %>
  <% end %>
  <%= link_to "Create", new_listing_path, class: "btn btn-outline-dark mx-2" %>
</div>

app/views/listings/new.html.erb
<% content_for :title, "New listing" %>



<%= render "form", listing: @listing %>

app/views/listings/show.html.erb
<div class="container mt-5">
<div class="d-flex flex-column align-items-center">


  
    <div class="card shadow-lg " style="width: 100%; max-width: 500px;"> 
      <div class="card-body">
        <h5 class="card-title"><strong><%= @listing.title.upcase %></strong></h5><hr>
        <p class="card-text">
        <b>Descrption: <%= @listing.description %> </b> <br>
        <b>User: <%= @listing.user.name %>  </b>  <br>
        <b>Price: <%= @listing.price %> </b>  <br>
        <b>Crop: <%= @listing.crop.name %> </b>  <br>
        
        
    
    
        <div class="d-flex justify-content-center mt-3">
        <%= link_to "Edit this Product", edit_listing_path(@listing), class: "btn btn-outline-success mx-2" %> 
        <%= link_to "Back ", listings_path, class: "btn btn-outline-dark mx-2" %>
        <%= button_to "Destroy this Product", @listing, class: "btn btn-outline-danger mx-2", method: :delete %>
        </div>
    </div>
</div>