config/routes.rb
Rails.application.routes.draw do
  
  
  get 'login', to: 'sessions#new', as: 'new_session'  
  post 'login', to: 'sessions#create', as: 'session'   
  get 'logout', to: 'sessions#destroy'
  
  resources :listings
  resources :crops_labels
  resources :crop_categories
  resources :crops
  resources :users
  resources :password_resets, only: [:new, :create, :edit, :update]
  

  

  get "password_resets/new"
  get "password_resets/edit"
  
  get '/profile', to: 'users#profile', as: 'profile'

  
  root to: "home#index"
  #root "users#new"
  get "users/index"
  get "home/about"

  #login/logout routes
  
 
  #get "up" => "rails/health#show", as: :rails_health_check


end

app/models/user.rb
class User < ApplicationRecord


  has_secure_password
  has_many :listings, dependent: :destroy
  has_many :crops, dependent: :destroy

  has_one_attached :photo


  # Reset Password
  def generate_password_reset_token!
    update!(
      reset_password_token: SecureRandom.urlsafe_base64,
      reset_password_sent_at: Time.current
    )
  end

  def password_reset_token_valid?
    reset_password_sent_at && reset_password_sent_at > 2.hours.ago
  end

  def reset_password!(new_password)
    update!(
      reset_password_token: nil,
      password: new_password
    )
  end
  
  

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_login, only: %i[profile show edit update destroy]           
  before_action :set_user, only: %i[show edit update destroy ] 
  before_action :authorize_user!, only: %i[show edit update destroy]
  
  

  
  def index
    redirect_to root_path, alert: "Access denied."
  end

  def profile
    @user = current_user  
    redirect_to @user
  end

  
  def show
   
  end

  
  def new
    @user = User.new
  end

 
  def edit
  end

  
  def create
    @user = User.new(user_params)
     

    respond_to do |format|
      if @user.save
        
        UserMailer.welcome_email(@user).deliver_later
        format.html { redirect_to @user, notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        
      end
    end
  end

  
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    
    @user.destroy!
    
    session[:user_id] = nil   
    respond_to do |format|
      format.html { redirect_to new_session_path, notice: "User was successfully deleted.", status: :see_other }
      format.json { head :no_content }
    end
  end

  private

   
    def set_user
      @user = User.find(params[:id])
    end

    
    def authorize_user!
      unless @user == current_user
        redirect_to root_path, notice: "Access denied."
      end
    end

    
    # def require_login
    #   unless current_user
    #     redirect_to new_session_path, notice: "Please log in to access this page."
    #   end
    # end

  
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation, :location, :role, :photo)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>

  <% if user.errors.any? %>
    <div class="alert alert-danger">
      <h4><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h4>
      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="container py-5 h-100">
    <div class="row justify-content-center align-items-center h-100">
      <div class="col-12 col-md-8 col-lg-7">
        <div class="card bg-dark text-white shadow-lg" style="border-radius: 15px;">
          <div class="card-body p-5">

            <h3 class="fw-bold mb-2 text-uppercase text-center">Register</h3>

            <div class="form-group mb-3">
              <%= form.label :name, class: "form-label" %>
              <%= form.text_field :name, required: true, class: "form-control", placeholder: "Enter your full name" %>
            </div>

            <div class="form-group mb-3">
              <%= form.label :email, class: "form-label" %>
              <%= form.email_field :email, required: true, class: "form-control", placeholder: "Enter your email" %>
            </div>

            <div class="form-group mb-3">
              <%= form.label :password, class: "form-label" %>
              <%= form.password_field :password, required: true, class: "form-control", placeholder: "Enter your password" %>
            </div>

            <div class="form-group mb-3">
              <%= form.label :password_confirmation, "Confirm Password", class: "form-label" %>
              <%= form.password_field :password_confirmation, required: true, class: "form-control", placeholder: "Re-enter your password" %>
            </div>

            <div class="form-group mb-3">
              <%= form.label :location, class: "form-label" %>
              <%= form.text_field :location, class: "form-control", placeholder: "Enter your location" %>
            </div>

            <div class="form-group mb-4">
              <%= form.label :role, class: "form-label" %>
              <%= form.select :role, options_for_select([['Farmer', 'farmer'], ['Buyer', 'buyer']]), { prompt: 'Select Role' }, class: "form-select", required: true %>
            </div>

            <div class="field">
              <%= form.label :profile_picture %>
              <%= form.file_field :photo %>
            </div>
            <br><br><hr>

            <div class="d-grid">
              <%= form.submit 'Sign Up', class: "btn btn-outline-light btn-lg px-5" %>
            </div>

          </div>
        </div>
      </div>
    </div>
  </div>

<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
<body class="bg-dark text-white">

<div class="card shadow text-bg-light text-black mb-3" style="width: 100%; max-width: 300px;">


  <h2 class="card-title"><%= user.name %></h2>
  <hr>
  <p>
    <strong>Email:</strong>
    <%= user.email %>
  </p>
  <p>
    <strong>Password:</strong>
    <%= user.password_digest %>
  </p>

  <p>
    <strong>Location:</strong>
    <%= user.location %>
  </p>

  <p>
    <strong>Role:</strong>
    <%= user.role %>
  </p>

</div>
</div>
</div>
</body>

app/views/users/edit.html.erb
<%= form_with(model: @user, local: true) do |form| %>

    <% if @user.errors.any? %>
      <div class="alert alert-danger">
        <h4><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h4>
        <ul>
          <% @user.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  
    <div class="container py-5 h-100">
      <div class="row justify-content-center align-items-center h-100">
        <div class="col-12 col-md-8 col-lg-7">
          <div class="card bg-dark text-white shadow-lg" style="border-radius: 15px;">
            <div class="card-body p-5">
  
              <h3 class="fw-bold mb-2 text-uppercase text-center">UPDATE</h3>
  
              <div class="form-group mb-3">
                <%= form.label :name, class: "form-label" %>
                <%= form.text_field :name, required: true, class: "form-control", placeholder: "Enter your full name" %>
              </div>
  
              <div class="form-group mb-3">
                <%= form.label :email, class: "form-label" %>
                <%= form.email_field :email, required: true, class: "form-control", placeholder: "Enter your email" %>
              </div>
  
              
  
              <div class="form-group mb-3">
                <%= form.label :location, class: "form-label" %>
                <%= form.text_field :location, class: "form-control", placeholder: "Enter your location" %>
              </div>
  
              <div class="form-group mb-4">
                <%= form.label :role, class: "form-label" %>
                <%= form.select :role, options_for_select([['Farmer', 'farmer'], ['Buyer', 'buyer']]), { prompt: 'Select Role' }, class: "form-select", required: true %>
              </div>

              <div class="field">
              <%= form.label :profile_picture %>
              <%= form.file_field :photo %>
              </div>
              
                <br> <br> <hr>
              <div class="d-grid">
                <%= form.submit 'Update', class: "btn btn-outline-light btn-lg px-5" %>
              </div>
  
            </div>
          </div>
        </div>
      </div>
    </div>
  
  <% end %>
  

app/views/users/index.html.erb
<% content_for :title, "Users" %>

<h1 class="text-center my-4">Users</h1>

<div class="container">
  <div class="row justify-content-center">
    <% @users.each do |user| %>
      <div class="col-12 col-md-4 d-flex justify-content-center mb-4">
        <div class="card shadow" style="width: 100%; max-width: 350px;">  <!-- Increased max-width -->
          <div class="card-body">
            <h5 class="card-title"><%= user.name %></h5>
            <p class="card-text">
              Email: <%= user.email %><br>
              Role: <%= user.role %>
            </p>
          </div>
          <div class="card-footer text-center">
            <%= link_to "Show this user", user, class: "btn btn-outline-dark" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<% content_for :title, "New user" %>



<%= render "form", user: @user %>

app/views/users/show.html.erb
<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-lg-8 col-md-10 col-sm-12">

      
      <div class="card shadow-lg rounded-4">
        <div class="card-body">
            
            <div class="container mt-5">
              <div class="row justify-content-center align-items-center">
              <div class="col-md-3 text-center">
              <% if @user.photo.attached? %>
                <%= image_tag @user.photo, class: 'rounded-circle img-fluid shadow', style: 'width: 150px; height: 150px; border: 3px solid #f0f0f0;' %>
              <% else %>
                <%= image_tag 'user.png', class: 'rounded-circle img-fluid shadow', style: 'width: 150px; height: 150px; border: 3px solid #f0f0f0;' %>
              <% end %>
            </div>

            <div class="col-md-6">
              <div class="p-3 border rounded shadow-sm bg-light text-center">
                <h4 class="font-weight-bold text-dark mb-1">Name: <%= @user.name.upcase %></h4>
                <p class=" mb-1"> <%= @user.email %></p>
                <p class="mb-1">You are a <%= @user.role.upcase %></p>
                <p class=" mb-0">Your Location: <%= @user.location.upcase %></p>
              </div>
            </div>
            </div>
            </div>
            <br>
            <hr>

          <div class="row text-center">
            <div class="col-md-4 mb-4">
              <%= link_to new_crop_path, class: "btn btn-light rounded-pill shadow-sm p-3 w-100" do %>
              
                <h6 class="mt-2">Add New Crop</h6>
              <% end %>
            </div>
            <div class="col-md-4 mb-4">
              <%= link_to listings_path, class: "btn btn-light rounded-pill shadow-sm p-3 w-100" do %>
               
                <h6 class="mt-2">Crops Listing</h6>
              <% end %>
            </div>
            <div class="col-md-4 mb-4">
              <%= link_to crops_labels_path(@user), class: "btn btn-light rounded-pill shadow-sm p-3 w-100" do %>
              
                <h6 class="mt-2">Crop Label</h6>
              <% end %>
            </div>

            <div class="col-md-4 mb-4">
              <%= link_to crop_categories_path(@user), class: "btn btn-light rounded-pill shadow-sm p-3 w-100" do %>
          
                <h6 class="mt-2">Crop Category</h6>
              <% end %>
            </div>

            <div class="col-md-4 mb-4">
              <%= link_to edit_user_path(@user), class: "btn btn-light rounded-pill shadow-sm p-3 w-100" do %>
               
                <h6 class="mt-2">User Settings</h6>
              <% end %>
            </div>
          </div>

        </div>
      </div>

     
      <div class="d-flex justify-content-center mt-4">
        
        
        <%= button_to "Delete Account", @user, class: "btn btn-danger rounded-pill px-4 py-2 mx-2", method: :delete, data: { confirm: 'Are you sure you want to delete your account?' } %>
      </div>

    </div>
  </div>
</div>