config/routes.rb
Rails.application.routes.draw do
  
  
  get 'login', to: 'sessions#new', as: 'new_session'  
  post 'login', to: 'sessions#create', as: 'session'   
  get 'logout', to: 'sessions#destroy'
  
  resources :listings
  resources :crops_labels
  resources :crop_categories
  resources :crops
  resources :users
  resources :password_resets, only: [:new, :create, :edit, :update]
  

  

  get "password_resets/new"
  get "password_resets/edit"
  
  get '/profile', to: 'users#profile', as: 'profile'

  
  root to: "home#index"
  #root "users#new"
  get "users/index"
  get "home/about"

  #login/logout routes
  
 
  #get "up" => "rails/health#show", as: :rails_health_check


end

app/models/crop.rb
class Crop < ApplicationRecord
  
  belongs_to :user 
  has_many :crops_label, dependent: :destroy
  has_many :crop_categories, through: :crops_label
  has_many :listings

end

app/controllers/crops_controller.rb
class CropsController < ApplicationController
  before_action :set_crop, only: %i[ show edit update destroy ]

  # GET /crops or /crops.json
  def index
    @crops = Crop.all
  end

  # GET /crops/1 or /crops/1.json
  def show
  end

  # GET /crops/new
  def new
    @crop = Crop.new
  end

  # GET /crops/1/edit
  def edit
  end

  # POST /crops or /crops.json
  def create
    @crop = Crop.new(crop_params)

    respond_to do |format|
      if @crop.save
        format.html { redirect_to @crop, notice: "Crop was successfully created." }
        format.json { render :show, status: :created, location: @crop }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @crop.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /crops/1 or /crops/1.json
  def update
    respond_to do |format|
      @crop = Crop.find(params[:id])
        if @crop.listings.exists?
          redirect_to crops_path, notice: "Cannot delete crop because it has associated listings."
        else
      @crop.destroy
        redirect_to crops_path, notice: "Crop deleted successfully."
  end
    end
  end

  # DELETE /crops/1 or /crops/1.json
  def destroy
    @crop.destroy!

    respond_to do |format|
      format.html { redirect_to crops_path, status: :see_other, notice: "Crop was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_crop
      @crop = Crop.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def crop_params
      params.expect(crop: [ :name, :description, :user_id ])
    end
end

app/helpers/crops_helper.rb
module CropsHelper
end

app/views/crops/_crop.html.erb
<div id="<%= dom_id crop %>">

<body class="bg-dark text-white">

<div class="card shadow text-bg-light text-black mb-3 card-color" style="width: 100%; max-width: 300px;">


  <h2 class="card-title">
    <strong><%= crop.name.upcase %></strong>
  </h2><hr>

  <p>
    <strong>Description:</strong>
    <%= crop.description %>
  </p>

  <p>
    <strong>User:</strong>
    <%= crop.user.name %>
  </p>
  <p>
  <%= link_to "Show this crop", crop , class: "btn btn-outline-dark mx-2"%>
  
  <%= link_to "New crop", new_crop_path, class: "btn btn-outline-dark mx-2" %>
  </p>

</div>

app/views/crops/_form.html.erb
<%= form_with(model: crop) do |form| %>
  <% if crop.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(crop.errors.count, "error") %> prohibited this crop from being saved:</h2>

      <ul>
        <% crop.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <div class="container py-5 h-100">
    <div class="row justify-content-center align-items-center h-150">
      <div class="col-12 col-lg-9 col-xl-7">
        <div class="card shadow-2-strong card-registration" style="border-radius: 15px;">
          <div class="card-body p-4 p-md-5">
          <h3 class="mb-4 pb-2 pb-md-0 mb-md-5">Crop Information</h3>
  <form>

    <div class="field form-group">
      <%=form.label :name , style: "display: block" %>
      <%= form.text_field :name, required:true,class:"form-control" , placeholder:"Enter Crop name"%>
    </div>
    <br>

    <div class="field form-group">
      <%= form.label :description, style: "display: block" %>
      <%= form.text_field :description,required: true ,class:"form-control" ,placeholder:"Descrption"  %>
    </div>
    <br>

    <div class="field form-group">
    <%= form.label :user_id, "Select User", style: "display: block" %>
    <%= form.collection_select :user_id, User.all, :id, :name, prompt: "Choose a user", class: "form-control" %>
    </div>
    <br>
  

 
    <div style="text-align: center; margin-top: 20px;",class="btn btn-primary">
      <%= form.submit %>
    </div>
  </form>
          </div>
        </div>
      </div>
    </div>
  </div>


<% end %>

app/views/crops/edit.html.erb
<% content_for :title, "Editing crop" %>



<%= render "form", crop: @crop %>

<br>

app/views/crops/index.html.erb
<% content_for :title, "Crops" %>

<h1>Crops</h1>

<div id="crops">
  <% @crops.each do |crop| %>
    <%= render crop %>
  <% end %>
    <%= link_to "Add crop", new_crop_path, class: "btn btn-outline-dark mx-2" %>
</div>

app/views/crops/new.html.erb
<% content_for :title, "New crop" %>



<%= render "form", crop: @crop %>

<br>

<div>
  <%= link_to "Back to crops", crops_path %>
</div>

app/views/crops/show.html.erb
<div class="container mt-5">
<div class="d-flex flex-column align-items-center">


  
    <div class="card shadow-lg card-color" style="width: 100%; max-width: 500px;"> 
      <div class="card-body">
        <h5 class="card-title"><strong><%= @crop.name.upcase %></strong></h5><hr>
        <p class="card-text">
        <b>Descrption: <%= @crop.description %><br></b>
        <b>User: <%= @crop.user.name %> [ID: <%= @crop.user.id %>]<br>
        </b>
    
    
        <div class="d-flex justify-content-center mt-4">
        <%= link_to "Edit this crop", edit_crop_path(@crop), class: "btn btn-outline-success mx-2" %> 
        <%= link_to "Back to crops", crops_path, class: "btn btn-outline-dark mx-2" %>
        <%= button_to "Destroy this crop", @crop, class: "btn btn-outline-danger mx-2", method: :delete %>
      </div>
  </div>
</div>